// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Softplan.Data.Context;

namespace Softplan.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211004150225_database_ef")]
    partial class database_ef
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Softplan.Domain.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idcategory")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("description");

                    b.Property<double>("ProfitMargin")
                        .HasColumnType("float")
                        .HasColumnName("profit_margin");

                    b.HasKey("Id");

                    b.ToTable("category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Brinquedos",
                            ProfitMargin = 0.25
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bebidas",
                            ProfitMargin = 0.29999999999999999
                        },
                        new
                        {
                            Id = 3,
                            Description = "Informática",
                            ProfitMargin = 0.10000000000000001
                        },
                        new
                        {
                            Id = 4,
                            Description = "Softplan",
                            ProfitMargin = 0.050000000000000003
                        },
                        new
                        {
                            Id = 5,
                            Description = "Toda e qualquer outra categoria informada",
                            ProfitMargin = 0.14999999999999999
                        });
                });

            modelBuilder.Entity("Softplan.Domain.Entities.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idproduct")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CostPrice")
                        .HasColumnType("float")
                        .HasColumnName("cost_price");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("createat");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("description");

                    b.Property<int>("IdCategory")
                        .HasColumnType("int")
                        .HasColumnName("idcategory");

                    b.Property<double>("SalePrice")
                        .HasColumnType("float")
                        .HasColumnName("sale_price");

                    b.HasKey("Id");

                    b.HasIndex("IdCategory");

                    b.ToTable("product");
                });

            modelBuilder.Entity("Softplan.Domain.Entities.ProductEntity", b =>
                {
                    b.HasOne("Softplan.Domain.Entities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
